// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GCToLS.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GCToLS {

  /// <summary>Holder for reflection information generated from GCToLS.proto</summary>
  public static partial class GCToLSReflection {

    #region Descriptor
    /// <summary>File descriptor for GCToLS.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCToLSReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxHQ1RvTFMucHJvdG8SBkdDVG9MUyJaCghBc2tMb2dpbhIcCgVtc2dpZBgB",
            "IAEoDjINLkdDVG9MUy5Nc2dJRBIQCghwbGF0Zm9ybRgCIAEoDRILCgN1aW4Y",
            "AyABKAkSEQoJc2Vzc2lvbmlkGAQgASgJKmgKBU1zZ0lEEgoKBnVua25vdxAA",
            "EhoKFGVNc2dUb0xTRnJvbUdDX0JlZ2luEIDAAhIdChdlTXNnVG9MU0Zyb21H",
            "Q19Bc2tMb2dpbhCBwAISGAoSZU1zZ1RvTFNGcm9tR0NfRW5kEIrAAmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GCToLS.MsgID), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GCToLS.AskLogin), global::GCToLS.AskLogin.Parser, new[]{ "Msgid", "Platform", "Uin", "Sessionid" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MsgID {
    [pbr::OriginalName("unknow")] Unknow = 0,
    [pbr::OriginalName("eMsgToLSFromGC_Begin")] EMsgToLsfromGcBegin = 40960,
    [pbr::OriginalName("eMsgToLSFromGC_AskLogin")] EMsgToLsfromGcAskLogin = 40961,
    [pbr::OriginalName("eMsgToLSFromGC_End")] EMsgToLsfromGcEnd = 40970,
  }

  #endregion

  #region Messages
  public sealed partial class AskLogin : pb::IMessage<AskLogin> {
    private static readonly pb::MessageParser<AskLogin> _parser = new pb::MessageParser<AskLogin>(() => new AskLogin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AskLogin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GCToLS.GCToLSReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskLogin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskLogin(AskLogin other) : this() {
      msgid_ = other.msgid_;
      platform_ = other.platform_;
      uin_ = other.uin_;
      sessionid_ = other.sessionid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskLogin Clone() {
      return new AskLogin(this);
    }

    /// <summary>Field number for the "msgid" field.</summary>
    public const int MsgidFieldNumber = 1;
    private global::GCToLS.MsgID msgid_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GCToLS.MsgID Msgid {
      get { return msgid_; }
      set {
        msgid_ = value;
      }
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 2;
    private uint platform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "uin" field.</summary>
    public const int UinFieldNumber = 3;
    private string uin_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uin {
      get { return uin_; }
      set {
        uin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sessionid" field.</summary>
    public const int SessionidFieldNumber = 4;
    private string sessionid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sessionid {
      get { return sessionid_; }
      set {
        sessionid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AskLogin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AskLogin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Msgid != other.Msgid) return false;
      if (Platform != other.Platform) return false;
      if (Uin != other.Uin) return false;
      if (Sessionid != other.Sessionid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Msgid != 0) hash ^= Msgid.GetHashCode();
      if (Platform != 0) hash ^= Platform.GetHashCode();
      if (Uin.Length != 0) hash ^= Uin.GetHashCode();
      if (Sessionid.Length != 0) hash ^= Sessionid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Msgid != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Msgid);
      }
      if (Platform != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Platform);
      }
      if (Uin.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uin);
      }
      if (Sessionid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Sessionid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Msgid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Msgid);
      }
      if (Platform != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Platform);
      }
      if (Uin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uin);
      }
      if (Sessionid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sessionid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AskLogin other) {
      if (other == null) {
        return;
      }
      if (other.Msgid != 0) {
        Msgid = other.Msgid;
      }
      if (other.Platform != 0) {
        Platform = other.Platform;
      }
      if (other.Uin.Length != 0) {
        Uin = other.Uin;
      }
      if (other.Sessionid.Length != 0) {
        Sessionid = other.Sessionid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            msgid_ = (global::GCToLS.MsgID) input.ReadEnum();
            break;
          }
          case 16: {
            Platform = input.ReadUInt32();
            break;
          }
          case 26: {
            Uin = input.ReadString();
            break;
          }
          case 34: {
            Sessionid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
