// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LSToSDK.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LSToSDK {

  /// <summary>Holder for reflection information generated from LSToSDK.proto</summary>
  public static partial class LSToSDKReflection {

    #region Descriptor
    /// <summary>File descriptor for LSToSDK.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LSToSDKReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1MU1RvU0RLLnByb3RvEgdMU1RvU0RLIk0KC1VzZXJMb2dpbjkxEh0KBW1n",
            "c2lkGAEgASgOMg4uTFNUb1NESy5Nc2dJRBIRCglsb2dpbmluZm8YAiABKAkS",
            "DAoEZ2NpZBgEIAEoBSozCgVNc2dJRBIKCgZ1bmtub3cQABIeChplTXNnVG9H",
            "Q0Zyb21CU185MVVzZXJMb2dpbhABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LSToSDK.MsgID), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LSToSDK.UserLogin91), global::LSToSDK.UserLogin91.Parser, new[]{ "Mgsid", "Logininfo", "Gcid" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MsgID {
    [pbr::OriginalName("unknow")] Unknow = 0,
    [pbr::OriginalName("eMsgToGCFromBS_91UserLogin")] EMsgToGcfromBs91UserLogin = 1,
  }

  #endregion

  #region Messages
  public sealed partial class UserLogin91 : pb::IMessage<UserLogin91> {
    private static readonly pb::MessageParser<UserLogin91> _parser = new pb::MessageParser<UserLogin91>(() => new UserLogin91());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserLogin91> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LSToSDK.LSToSDKReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserLogin91() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserLogin91(UserLogin91 other) : this() {
      mgsid_ = other.mgsid_;
      logininfo_ = other.logininfo_;
      gcid_ = other.gcid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserLogin91 Clone() {
      return new UserLogin91(this);
    }

    /// <summary>Field number for the "mgsid" field.</summary>
    public const int MgsidFieldNumber = 1;
    private global::LSToSDK.MsgID mgsid_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LSToSDK.MsgID Mgsid {
      get { return mgsid_; }
      set {
        mgsid_ = value;
      }
    }

    /// <summary>Field number for the "logininfo" field.</summary>
    public const int LogininfoFieldNumber = 2;
    private string logininfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Logininfo {
      get { return logininfo_; }
      set {
        logininfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gcid" field.</summary>
    public const int GcidFieldNumber = 4;
    private int gcid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Gcid {
      get { return gcid_; }
      set {
        gcid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserLogin91);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserLogin91 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mgsid != other.Mgsid) return false;
      if (Logininfo != other.Logininfo) return false;
      if (Gcid != other.Gcid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mgsid != 0) hash ^= Mgsid.GetHashCode();
      if (Logininfo.Length != 0) hash ^= Logininfo.GetHashCode();
      if (Gcid != 0) hash ^= Gcid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mgsid != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Mgsid);
      }
      if (Logininfo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Logininfo);
      }
      if (Gcid != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Gcid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mgsid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Mgsid);
      }
      if (Logininfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Logininfo);
      }
      if (Gcid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gcid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserLogin91 other) {
      if (other == null) {
        return;
      }
      if (other.Mgsid != 0) {
        Mgsid = other.Mgsid;
      }
      if (other.Logininfo.Length != 0) {
        Logininfo = other.Logininfo;
      }
      if (other.Gcid != 0) {
        Gcid = other.Gcid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            mgsid_ = (global::LSToSDK.MsgID) input.ReadEnum();
            break;
          }
          case 18: {
            Logininfo = input.ReadString();
            break;
          }
          case 32: {
            Gcid = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
